# Generated by Django 4.0.3 on 2022-04-01 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothing',
            name='attire',
            field=models.CharField(default='Sport, Casual, Business', max_length=32),
        ),
        migrations.AlterField(
            model_name='clothing',
            name='color',
            field=models.CharField(default='Enter Color Here', max_length=32),
        ),
        migrations.AlterField(
            model_name='clothing',
            name='color_type',
            field=models.CharField(default='Enter color based on color type. See Attached Image', max_length=32),
        ),
        migrations.AlterField(
            model_name='clothing',
            name='description',
            field=models.CharField(default='Please Enter a Brief Description', max_length=32),
        ),
        migrations.AlterField(
            model_name='clothing',
            name='type',
            field=models.CharField(default='Top, Bottom, Shoes', max_length=32),
        ),
    ]
